apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/influxdb"
    type: DirectoryOrCreate
  claimRef:
    name: influxdb-pv-disk
    namespace: default

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi