apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
  labels:
    app: influxdb
type: Opaque
stringData:
  INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf
  INFLUXDB_ADMIN_USER: bshang
  INFLUXDB_ADMIN_PASSWORD: mypass
  INFLUXDB_DB: telegraf
  INFLUXDB_USER: bshang
  INFLUXDB_USER_PASSWORD: mypass

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  labels:
    app: influxdb
data:
  influxdb.conf: |
    bind-address = "127.0.0.1:8088"
    [meta]
      dir = "/var/lib/influxdb/meta"
    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      trace-logging-enabled = true
    [http]
      bind-address = ":8086"
      log-enabled = true
    [[graphite]]
      database = "telegraf"
      protocol = "tcp"
