apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/mnt/influxdb"
    type: DirectoryOrCreate
  claimRef:
    name: influxdb-pvc
    namespace: default

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
