kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  labels:
    app: mysql
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/pv-mysql"