apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteMany # or ReadWriteOnce?
  resources:
    requests:
      storage: 2Gi