apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.238
  selector:
    app: grafana
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-container
        image: grafana-image
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
          name: https
        volumeMounts:
          - name: grafana-config
            subPath: grafana.ini
            mountPath: /etc/grafana/grafana.ini
            readOnly: true
        envFrom:
          - secretRef:
              name: grafana-secret
      volumes:
        - name: grafana-config
          configMap:
              name: grafana-config
