apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.231
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  - port: 22
    name: ssh
    protocol: TCP
    targetPort: 22
