apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.99.233
  ports:
  - port: 5000
    name: pma-port
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: phpmyadmin-pod
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin-container
        image: phpmyadmin-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
      - name: nginx-container
        image: phpmyadmin-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        # env:
        # - name: PMA_HOST
        #   value: mysql-service
        # - name: PMA-PORT
        #   value: "3306"
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom:
        #       secretKeyRef:
        #         name: mysql-secret
        #         key: root_password
