apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.99.231
  ports:
  - port: 5050
    name: port
    targetPort: 5050
