apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
  labels:
    app: telegraf
spec:
  selector:
    app: telegraf
  ports:
  - port: 999
    name: telegraf-temp
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      name: telegraf-pod
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf-container
        image: telegraf-image
        imagePullPolicy: Never
        volumeMounts:
          - name: telegraf-config
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf.conf
            readOnly: true
          - name: docker-socket
            mountPath: /var/run/docker.sock
      volumes:
        - name: telegraf-config
          configMap:
              name: telegraf-config
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
