apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-configmap
  labels:
    app: telegraf
data:
  telegraf.conf: |
    [global_tags]
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      hostname = ""
      omit_hostname = true
    [[outputs.influxdb]]
      urls = ["$INFLUXDB_URL"]
      database = "$INFLUXDB_DB"
      username = "$INFLUXDB_USER"
      password = "$INFLUXDB_USER_PASSWORD"
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      gather_services = false
      container_name_include = []
      container_name_exclude = []
      perdevice = true
      total = true
      docker_label_include = []
      docker_label_exclude = []
      tag_env = ["JAVA_HOME", "HEAP_SIZE"]

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: telegraf-service
#   labels:
#     app: telegraf
# spec:
#   selector:
#     app: telegraf
#   ports:
#     - name: port
#       port: 999
#   type: LoadBalancer
#   loadBalancerIP: 192.168.99.235

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      name: telegraf-pod
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf-container
        image: telegraf-image
        imagePullPolicy: Never
        volumeMounts:
          - name: telegraf-config
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf.conf
            readOnly: true
          - name: docker-socket
            mountPath: /var/run/docker.sock
        envFrom:
          - secretRef:
              name: telegraf-secret
      volumes:
        - name: telegraf-config
          configMap:
              name: telegraf-configmap
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
